COMPONENT=ContourTrackingAppC
CFLAGS += -DTOSH_DATA_LENGTH=55

PFLAGS += -DTIMESYNC_RATE=3
#PFLAGS += -DTIMESYNC_DEBUG
PFLAGS += -I$(TOSDIR)/lib/ftsp -I$(TOSDIR)/lib/net/ -I$(TOSDIR)/lib/net/ctp  -I$(TOSDIR)/lib/net/4bitle



include $(MAKERULES)
